command: python main.py
envs:
  root: ../../data/MovieLens1M
  dataset: MovieLens1M
  device: 0,1,2,3
params:
  criterion: [BPRLoss, BCELoss]
  weight_decay: [0, 1e-8, 1e-6, 1e-4, 5e-4]
  regularizer: [ortho, l2, l1]
  learning_rate: [1e-3, 5e-3]
defaults:
  optimizer: adam
  batch_size: 256
  embedding_dim: 32
  epochs: 20